### ISSUE TITLE
벽과 바닥 구분

### ISSUE THREAD

**Issue by Dophian** [PuPandora/Magical-Totia#3]
![Honeycam 2024-09-13 14-40-07](https://github.com/user-attachments/assets/306baaf1-8f3a-422a-9b6c-07e9992865e5)

공중에서 벽에 닿을 시 바닥으로 인식하여 걷는 애니메이션이 재생되는 현상 수정 바람

+ 위 사진에는 나오지 않았으나 옆이 아닌 머리에 벽이 닿아도 걷는 모습이 나옴

**Comment by PuPandora** [comment]
이 버그의 발생 이유는 플레이어가 땅에 닿음 -> 애니메이션에서 점프 상태 조절이 원인이었습니다.
이전 커밋에서 플레이어의 점프 횟수 제한을 추가하다, 플레이어가 땅 오브젝트의 윗 부분에 닿았을 때만 땅에 닿았다는 판정을 추가하였습니다. 이 과정에서 애니메이션이 점프 상태를 변경하는 조건이 달라지게 되어, 이제 더이상 플레이어의 옆이나 위가 땅에 닿았을 경우 걷는 애니메이션이 재생되지 않습니다.

[283daa0ac81b9a408c5b5647a9e60a3fd9e961c0](https://github.com/PuPandora/Magical-Totia/blob/6a6d3fef50cf6580b7e586aaa921886aff3d311f/Assets/Scripts/Player.cs#L131-L135)
